name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: 46.101.43.93
        username: ${{ secrets.DIGITALOCEAN_U }}
        password: ${{ secrets.DIGITALOCEAN_P }}
        port: 22
        command_timeout: '10m'
        script: |
          cd /var/www/letstakeout
          git reset --hard HEAD
          git pull
          npm i
          npm run generate
